"""initial

Revision ID: 166799f70db9
Revises: 
Create Date: 2025-12-13 17:21:21.501966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166799f70db9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False, comment="User's email address (must be unique)"),
    sa.Column('name', sa.String(), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the user account is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was soft-deleted'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was soft-deleted'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was soft-deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('auth_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was soft-deleted'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_token_id'), 'auth_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_token_id'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
