"""created schema vision tracker

Revision ID: 746c29dbfce6
Revises: 166799f70db9
Create Date: 2026-01-09 00:53:30.956530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '746c29dbfce6'
down_revision: Union[str, Sequence[str], None] = '166799f70db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vision_id'), 'vision', ['id'], unique=False)
    op.create_table('theme',
    sa.Column('vision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vision_id'], ['vision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_id'), 'theme', ['id'], unique=False)
    op.create_table('track',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_id'), 'track', ['id'], unique=False)
    op.create_table('goal',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_id'), 'goal', ['id'], unique=False)
    op.create_table('phase',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_id'), 'phase', ['id'], unique=False)
    op.create_table('daily_commitment',
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('commitment_date', sa.Date(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_commitment_id'), 'daily_commitment', ['id'], unique=False)
    op.create_table('execution_log',
    sa.Column('commitment_id', sa.Integer(), nullable=False),
    sa.Column('actual_output', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commitment_id'], ['daily_commitment.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_id')
    )
    op.create_index(op.f('ix_execution_log_id'), 'execution_log', ['id'], unique=False)
    op.alter_column('auth_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was created',
               existing_comment='Timestamp when this record was soft-deleted',
               existing_nullable=False)
    op.drop_column('auth_token', 'updated_at')
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was created',
               existing_comment='Timestamp when this record was soft-deleted',
               existing_nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was updated',
               existing_comment='Timestamp when this record was soft-deleted',
               existing_nullable=False)
    op.alter_column('user', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was deleted',
               existing_comment='Timestamp when this record was soft-deleted',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was soft-deleted',
               existing_comment='Timestamp when this record was deleted',
               existing_nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was soft-deleted',
               existing_comment='Timestamp when this record was updated',
               existing_nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was soft-deleted',
               existing_comment='Timestamp when this record was created',
               existing_nullable=False)
    op.add_column('auth_token', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('auth_token', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='Timestamp when this record was soft-deleted',
               existing_comment='Timestamp when this record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_execution_log_id'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index(op.f('ix_daily_commitment_id'), table_name='daily_commitment')
    op.drop_table('daily_commitment')
    op.drop_index(op.f('ix_phase_id'), table_name='phase')
    op.drop_table('phase')
    op.drop_index(op.f('ix_goal_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_track_id'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_theme_id'), table_name='theme')
    op.drop_table('theme')
    op.drop_index(op.f('ix_vision_id'), table_name='vision')
    op.drop_table('vision')
    # ### end Alembic commands ###
