"""make track description nullable

Revision ID: 764bbf3d4d80
Revises: ae1fac635ff8
Create Date: 2026-05-05 14:18:48.618647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764bbf3d4d80'
down_revision: Union[str, Sequence[str], None] = 'ae1fac635ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('track', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Whether the user account is active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Whether the user account is active')
    op.alter_column('track', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
