"""initial

Revision ID: 8372011e4449
Revises: 
Create Date: 2025-12-13 02:40:35.772019

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8372011e4449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False, comment="User's email address (must be unique)"),
    sa.Column('name', sa.String(), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the user account is active'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was soft-deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
