"""initial

Revision ID: ae1fac635ff8
Revises: 
Create Date: 2026-04-30 19:05:22.473213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1fac635ff8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False, comment="User's email address (must be unique)"),
    sa.Column('name', sa.String(), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the user account is active'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('auth_token',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_auth_token_id'), 'auth_token', ['id'], unique=False)
    op.create_table('block',
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_id'), 'block', ['id'], unique=False)
    op.create_index('ix_block_owner_type_owner_id', 'block', ['owner_type', 'owner_id'], unique=False)
    op.create_table('daily_reflection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mood', sa.Enum('VERY_LOW', 'LOW', 'NEUTRAL', 'HIGH', 'VERY_HIGH', name='mood'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_reflection_user_date')
    )
    op.create_index(op.f('ix_daily_reflection_id'), 'daily_reflection', ['id'], unique=False)
    op.create_table('vision',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vision_id'), 'vision', ['id'], unique=False)
    op.create_table('theme',
    sa.Column('vision_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('preset_key', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vision_id'], ['vision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_id'), 'theme', ['id'], unique=False)
    op.create_table('track',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cadence_per_week', sa.Integer(), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_id'), 'track', ['id'], unique=False)
    op.create_table('goal',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('horizon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['track.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_id'), 'goal', ['id'], unique=False)
    op.create_table('phase',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('lifecycle', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETE', 'ABANDONED', name='phase_lifecycle'), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_id'), 'phase', ['id'], unique=False)
    op.create_index('ix_phase_one_active_per_goal', 'phase', ['goal_id'], unique=True, postgresql_where=sa.text("lifecycle = 'ACTIVE'"))
    op.create_table('daily_commitment',
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('commitment_date', sa.Date(), nullable=False),
    sa.Column('intent', sa.String(), nullable=False),
    sa.Column('expected_minutes', sa.Integer(), nullable=True),
    sa.Column('mve_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_commitment_id'), 'daily_commitment', ['id'], unique=False)
    op.create_table('execution_log',
    sa.Column('commitment_id', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was created'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='References the user who created this record'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when this record was updated'),
    sa.Column('updater_id', sa.Integer(), nullable=True, comment='References the user who last updated this record'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Timestamp when this record was deleted'),
    sa.Column('deleter_id', sa.Integer(), nullable=True, comment='References the user who deleted this record'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('energy_level IS NULL OR (energy_level BETWEEN 1 AND 5)', name='ck_execution_log_energy_level_range'),
    sa.ForeignKeyConstraint(['commitment_id'], ['daily_commitment.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_id')
    )
    op.create_index(op.f('ix_execution_log_id'), 'execution_log', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_log_id'), table_name='execution_log')
    op.drop_table('execution_log')
    op.drop_index(op.f('ix_daily_commitment_id'), table_name='daily_commitment')
    op.drop_table('daily_commitment')
    op.drop_index('ix_phase_one_active_per_goal', table_name='phase', postgresql_where=sa.text("lifecycle = 'ACTIVE'"))
    op.drop_index(op.f('ix_phase_id'), table_name='phase')
    op.drop_table('phase')
    op.drop_index(op.f('ix_goal_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_track_id'), table_name='track')
    op.drop_table('track')
    op.drop_index(op.f('ix_theme_id'), table_name='theme')
    op.drop_table('theme')
    op.drop_index(op.f('ix_vision_id'), table_name='vision')
    op.drop_table('vision')
    op.drop_index(op.f('ix_daily_reflection_id'), table_name='daily_reflection')
    op.drop_table('daily_reflection')
    op.drop_index('ix_block_owner_type_owner_id', table_name='block')
    op.drop_index(op.f('ix_block_id'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_auth_token_id'), table_name='auth_token')
    op.drop_table('auth_token')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
